name: Publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Remove Github Pages to allow publishing
        run: rm -rf docs
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.0
        with:
          credential: ${{ secrets.DART_PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: false
          dry_run: false